### ISSUE TITLE
ERD Design

### ISSUE THREAD

**Issue by Gregam3** [ASEGroup1/Tempus#12]
CLOB or BLOB? You decide.

**Comment by Gregam3** [comment]
@jamesfernando94 When this is done can you also attach an image of what the ERD looks like

**Comment by jamesfernando94** [comment]
![tempus](https://user-images.githubusercontent.com/11622177/53096254-9c56d600-3516-11e9-9578-9c3091654cd8.png)

**Comment by jamesfernando94** [comment]
@Gregam3 This should be completed now just needs a review
